language: node_js
node_js:
- '6'
notifications:
  slack:
    secure: vKriOYH2OYPUsd6s9AUw5nTyoGPEFY6SpwBiS1ufnkPzc+OfMsrBSTJqccQrIajLaThgtZybCAEKfzMunSUPHbhDm62/XDaKcLeTnyGUvDl3eloo51Lzm/BkpQNQ+kgN86/pcw2u+WrgS0Z6vPE5nYb6NVPkbR0lUfkB2OFjrTM/hpu6DVKigRiEbh6hmhq5fSOcPk3lw41U2VCOt9prvQG3bMGyBMLLBGQxBQbb66LjSqV2Bp8Vqd1AZJYh4yHlwW6pUEpa0oHJ1N2lu5jlEpmVoGBP/tWDyE1yWNkUdsDmkqWa06mFJPkRKpe885mQYzr+tUIpydJg0R/ECpI+hMqb+SNBgAfCjVjB5V6yN6yNlXUbKU4pL6mOYPLpbkMzj1kkUwldM5ASTvatLPUlYswkWE3OCIxsX6s7ku/jLdiEo3xeJ1AsmtAm3OrUN93ksHQ/0FljQJhTS8IZ1g8rOKvdktDI0D6GNJ9CayIIZo/xuLAb/sVdrAAn17s2Kgxg0nlhE+CQ7CqvG+Crws0efQqori/YpFQMIdEy13/8upLi02mH3WSAKLBvBdVfzobTgvSb5oQ+a2ZnvYLjGJwcYq8GbDSiYlNARpF/5Hx6XqqWr/SibZMTJNpupeSH1ctND40rvYdz2UBAmJG0M0jksr41CkXftw5rs4vZYKktHLc=
  email: false
