language: node_js
node_js:
- '5'
notifications:
  slack:
    secure: Q5WK9LS2WTvUo5LHHJKGi8tp4U+8ircYN0BTBbNStMwHgVDdOMwIF0TqHt/+qNqt7TbrjllnfJQfL7vXxdwrT7CKR56QXd6eYdf4DQgoenBGLDGO2wcbjT4xbdG9vuoUeaaM1dpYAC2aeFnXChH0VRkK/x5kyhq/idZIpz6h65HwAPZwATcIFBFj2oWN9L6oO3NBYTVXsoXHhwApr4mP3fLxjVQ5q/8INHx0Lgd9zrJZWxwdkYZZ6P95aEEeUtF0UPk0SwIKCga2eK7pGUkW3SFh8FjROFiHRTp3RetDAWv1Yhpfs+HGYyv/hQImlyz32kMvGDKS4+pggjkN8Jwedc/ttYaw0C5cpSFf7TfbdW+toUQiyFWov0QFtlnnIBhvkSk1BtOtnPT6YOcQ6Pn11T6ja0GpnfyRe/Tn2Cw5lvzeN4yF5h3lGaEOdfFncAxXxx7nCcacWa9FGLu2TBD8n77BydyID+7ju1irkmSsJXwvckKVESZcAKUNYybgXhv3dCxV6DvjB2OK1DrucnRNO9uBVQWMXN51ZM2OEAUw1kP0VGQ26uDqrJP0qaip8ERcGy6cbAubSF7eQBMGJHorUi+RsMsXD6Sw+0BfMA4TbED2psLMoq2E/jg3Eg56z7cy1by/MUc9CRPBQFa+IbOZgAlvcJr0aEHIIOOMQGIri3s=
  email: false
